spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  # 扫描mapper.xml文件
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 扫描实体类
  typeAliasesPackage: com.example.springbootmybatisplus.entity
  # 主键类型
  global-config:
    #0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    #插入的时候，0不set值时，不出现在sql中，1，2出现在sql中插入null或者空
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #全局表前缀
    db-config:
      table-prefix: tbl_
    #数据库大写下划线转换
    #capital-mode: true
  #自定义SQL注入器
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
logging:
  level:
    com.*: trace
